Repository Waultics/CryptoBook, pull requests merged in 2019-06, with the labels that each got.

#3 Removed the unnecessary conversion of the Time column to DateTime.
  CryptoBook/utils.py
Labels: enhancement

#1 Valid error return when API is called with empty POST document.
  CryptoBook/validators.py
  Dockerfile
Labels: bug, enhancement

#7 Complete documentation of the current project.
  .gitignore
  .travis.yml
  CONTRIBUTORS.md
  CryptoBook/api.py
  CryptoBook/utils.py
  CryptoBook/validators.py
  Dockerfile
  README.md
  assets/CryptoBook Box.png
  assets/CryptoBook Header.png
  assets/CryptoBook.png
  assets/psd/CryptoBook Box.psb
  assets/psd/CryptoBook.psb
  docs/Makefile
  docs/_static/CryptoBook Header.png
  docs/_static/CryptoBook Logo.png
  docs/api.rst
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/utils.rst
  docs/validators.rst
  requirements/base.txt
  requirements/dev.txt
  tests/__init__.py
Labels: enhancement

#12 Improved the general codebase.
  CryptoBook/api.py
  CryptoBook/utils.py
  CryptoBook/validators.py
  docs/api.rst
  tests/test_api.py
  tests/test_utils.py
  tests/test_validators.py
Labels: enhancement

#13 Added more tests to increase coverage.
  CryptoBook/api.py
  tests/test_api.py
  tests/test_validators.py
Labels: enhancement

#16 Bypassing CloudFare verification system via cfscrape.
  .travis.yml
  CryptoBook/api.py
  CryptoBook/utils.py
  CryptoBook/validators.py
  Dockerfile
  docs/api.rst
  examples/historical-pandas-cfbypass.py
  examples/historical-pandas.py
  requirements/base.txt
  requirements/dev.txt
  tests/test_api.py
  tests/test_validators.py
Labels: enhancement

#23 Change the codebase to follow the Black codestyle.
  CryptoBook/api.py
  CryptoBook/utils.py
  CryptoBook/validators.py
  examples/historical-pandas-cfbypass.py
  examples/historical-pandas.py
  tests/test_api.py
  tests/test_utils.py
  tests/test_validators.py
Labels: 📍proposition, 📦 enhancement

#26 Added extra measurements to bypass CloudFlare security, styling, and removed unused dependencies.
  CryptoBook/utils.py
  Dockerfile
Labels: 📦 enhancement, 🤦🏻‍♂️bug

#20 Changed Dockerfile for smaller container size (1.4gb to 522mb).
  Dockerfile
Labels: 📍proposition, 📦 enhancement

#28 Installed OpenSSL 1.1.1, and changed Dockerfile back to python:3 image.
  Dockerfile
Labels: 📦 enhancement, 🤦🏻‍♂️bug

#15 Low latency cryptocurrency information access via websockets.
  .travis.yml
  CryptoBook-js/Dockerfile
  CryptoBook-js/ccc-streamer-utilities.js
  CryptoBook-js/cryptocompare_streamer.js
  CryptoBook-js/tests/package-lock.json
  CryptoBook-js/tests/package.json
  CryptoBook-js/tests/test.js
  CryptoBook-py/CryptoBook/__init__.py
  CryptoBook-py/CryptoBook/api.py
  CryptoBook-py/CryptoBook/utils.py
  CryptoBook-py/CryptoBook/validators.py
  CryptoBook-py/Dockerfile
  CryptoBook-py/requirements/base.txt
  CryptoBook-py/requirements/dev.txt
  CryptoBook-py/tests/__init__.py
  CryptoBook-py/tests/test_api.py
  CryptoBook-py/tests/test_utils.py
  CryptoBook-py/tests/test_validators.py
  config.yml
  docker-compose.yml
  examples/historical_data_scraping/historical-pandas-cfbypass.py
  examples/historical_data_scraping/historical-pandas.py
  examples/real_time_data/simple_client_multiple_subs.py
  examples/real_time_data/simple_client_one_sub.py
  tests/__init__.py
Labels: 📦 enhancement

#30 Generally improved codebase (per #22), and small fixes.
  CryptoBook-py/CryptoBook/api.py
  CryptoBook-py/CryptoBook/errors.py
  CryptoBook-py/CryptoBook/handlers.py
  CryptoBook-py/CryptoBook/utils.py
  CryptoBook-py/tests/test_api.py
  CryptoBook-py/tests/test_handlers.py
  CryptoBook-py/tests/test_utils.py
  CryptoBook-py/tests/test_validators.py
  examples/Historical/historical-pandas-cfbypass.py
  examples/Historical/historical-pandas.py
  examples/Misc/exchange-info.py
Labels: 🐍 python, 📦 enhancement
